name: 'react-gh-pages'
description: 'Publish React app in Github Pages'
inputs:
  router-file:
    description: 'Path to file with BrowserRouter'
    required: true
    default: 'src/components/app/app.jsx'
  public-file:
    description: 'Path to index public file'
    required: true
    default: '/public/index.js'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
